[package]
name = "rocketjwt"
version = "0.1.1"
authors = ["Marirs <marirs@gmail.com>"]
description = "Barebones Rocket API Server with JWT auth"
keywords = ["rocket", "api", "jwt"]
edition = "2018"

[dependencies]


[profile.release]
codegen-units = 1
debug-assertions = false
debug = false
opt-level = 3
lto = true